### ISSUE TITLE
Background runner crashing

### ISSUE THREAD

**Issue by lucaswerkmeister** [lucaswerkmeister/tool-quickcategories#2]
```
Traceback (most recent call last):
  File "/srv/quickcategories/background_runner.py", line 61, in <module>
    flush_querytime(connection)
  File "/srv/quickcategories/querytime.py", line 66, in flush_querytime
    query_id = _querytext_store.acquire_id(connection, query)
  File "/tmp/venv/lib/python3.9/site-packages/cachetools/__init__.py", line 702, in wrapper
    k = key(self, *args, **kwargs)
TypeError: <lambda>() takes 2 positional arguments but 3 were given
```

**Comment by lucaswerkmeister** [comment]
Due to https://github.com/tkem/cachetools/commit/749a2c578b36cccf2c6c3366d3bfe2dd803142e5, I suspect.
